<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>fr.loghub</groupId>
        <artifactId>loghub-injectors-pom</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>loghub-injector-nettyphttp2</artifactId>
    <packaging>jar</packaging>

    <name>loghub-injector-nettyphttp2</name>
    <description>LogHub injector based on Netty HTTP/2</description>

    <properties>
        <netty.version>4.2.17.Final</netty.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-bom</artifactId>
                <version>${netty.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>fr.loghub</groupId>
            <artifactId>loghub-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec-http2</artifactId>
        </dependency>
    </dependencies>
</project>
